src/Entity/Etape.php
<?php

namespace App\Entity;

use App\Repository\EtapeRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: EtapeRepository::class)]
class Etape
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $texte_ambiance = null;

    #[ORM\Column(length: 255)]
    private ?string $libelle = null;

    #[ORM\OneToOne(mappedBy: 'premiereEtape', cascade: ['persist', 'remove'])]
    private ?Aventure $aventureDebutee = null;

    #[ORM\ManyToOne(inversedBy: 'etapes')]
    private ?Aventure $aventure = null;

    #[ORM\ManyToOne(inversedBy: 'finsPossibles')]
    private ?Aventure $finAventure = null;

    #[ORM\OneToMany(mappedBy: 'etapePrecedente', targetEntity: Alternative::class)]
    private Collection $alternatives;

    #[ORM\OneToMany(mappedBy: 'etape', targetEntity: Partie::class)]
    private Collection $parties;

    public function __construct()
    {
        $this->alternatives = new ArrayCollection();
        $this->parties = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTexteAmbiance(): ?string
    {
        return $this->texte_ambiance;
    }

    public function setTexteAmbiance(string $texte_ambiance): self
    {
        $this->texte_ambiance = $texte_ambiance;

        return $this;
    }

    public function getLibelle(): ?string
    {
        return $this->libelle;
    }

    public function setLibelle(string $libelle): self
    {
        $this->libelle = $libelle;

        return $this;
    }

    public function getAventureDebutee(): ?Aventure
    {
        return $this->aventureDebutee;
    }

    public function setAventureDebutee(?Aventure $aventureDebutee): self
    {
        // unset the owning side of the relation if necessary
        if ($aventureDebutee === null && $this->aventureDebutee !== null) {
            $this->aventureDebutee->setPremiereEtape(null);
        }

        // set the owning side of the relation if necessary
        if ($aventureDebutee !== null && $aventureDebutee->getPremiereEtape() !== $this) {
            $aventureDebutee->setPremiereEtape($this);
        }

        $this->aventureDebutee = $aventureDebutee;

        return $this;
    }

    public function getAventure(): ?Aventure
    {
        return $this->aventure;
    }

    public function setAventure(?Aventure $aventure): self
    {
        $this->aventure = $aventure;

        return $this;
    }

    public function getFinAventure(): ?Aventure
    {
        return $this->finAventure;
    }

    public function setFinAventure(?Aventure $finAventure): self
    {
        $this->finAventure = $finAventure;

        return $this;
    }

    /**
     * @return Collection<int, Alternative>
     */
    public function getalternatives(): Collection
    {
        return $this->alternatives;
    }

    public function addAlternative(Alternative $alternative): self
    {
        if (!$this->alternatives->contains($alternative)) {
            $this->alternatives->add($alternative);
            $alternative->setEtapePrecedente($this);
        }

        return $this;
    }

    public function removeAlternative(Alternative $alternative): self
    {
        if ($this->alternatives->removeElement($alternative)) {
            // set the owning side to null (unless already changed)
            if ($alternative->getEtapePrecedente() === $this) {
                $alternative->setEtapePrecedente(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Partie>
     */
    public function getParties(): Collection
    {
        return $this->parties;
    }

    public function addParty(Partie $party): self
    {
        if (!$this->parties->contains($party)) {
            $this->parties->add($party);
            $party->setEtape($this);
        }

        return $this;
    }

    public function removeParty(Partie $party): self
    {
        if ($this->parties->removeElement($party)) {
            // set the owning side to null (unless already changed)
            if ($party->getEtape() === $this) {
                $party->setEtape(null);
            }
        }

        return $this;
    }

    public function __toString()
    {
        return $this->libelle;
    }
}

src/Form/EtapeType.php
<?php

namespace App\Form;

use App\Entity\Etape;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class EtapeType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('texte_ambiance')
            ->add('libelle')
            ->add('aventureDebutee')
            ->add('aventure')
            ->add('finAventure')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Etape::class,
        ]);
    }
}

src/Controller/EtapeController.php
<?php

namespace App\Controller;

use App\Entity\Etape;
use App\Form\EtapeType;
use App\Repository\EtapeRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/etape')]
class EtapeController extends AbstractController
{
    #[Route('/', name: 'app_etape_index', methods: ['GET'])]
    public function index(EtapeRepository $etapeRepository): Response
    {
        $this->denyAccessUnlessGranted('ROLE_ADMIN', null, 'User tried to access a page without having ROLE_ADMIN');
        return $this->render('etape/index.html.twig', [
            'etapes' => $etapeRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_etape_new', methods: ['GET', 'POST'])]
    public function new(Request $request, EtapeRepository $etapeRepository): Response
    {
        $etape = new Etape();
        $form = $this->createForm(EtapeType::class, $etape);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $etapeRepository->save($etape, true);

            return $this->redirectToRoute('app_etape_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('etape/new.html.twig', [
            'etape' => $etape,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_etape_show', methods: ['GET'])]
    public function show(Etape $etape): Response
    {
        return $this->render('etape/show.html.twig', [
            'etape' => $etape,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_etape_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Etape $etape, EtapeRepository $etapeRepository): Response
    {
        $form = $this->createForm(EtapeType::class, $etape);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $etapeRepository->save($etape, true);

            return $this->redirectToRoute('app_etape_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('etape/edit.html.twig', [
            'etape' => $etape,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_etape_delete', methods: ['POST'])]
    public function delete(Request $request, Etape $etape, EtapeRepository $etapeRepository): Response
    {
        if ($this->isCsrfTokenValid('delete'.$etape->getId(), $request->request->get('_token'))) {
            $etapeRepository->remove($etape, true);
        }

        return $this->redirectToRoute('app_etape_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/etape/_delete_form.html.twig
<form method="post" action="{{ path('app_etape_delete', {'id': etape.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ etape.id) }}">
    <button class="btn">Delete</button>
</form>

templates/etape/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/etape/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Etape{% endblock %}

{% block body %}
    <h1>Edit Etape</h1>

    {{ include('etape/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_etape_index') }}">back to list</a>

    {{ include('etape/_delete_form.html.twig') }}
{% endblock %}

templates/etape/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Etape index{% endblock %}

{% block body %}
    <h1>Etape index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Texte_ambiance</th>
                <th>Libelle</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for etape in etapes %}
            <tr>
                <td>{{ etape.id }}</td>
                <td>{{ etape.texteAmbiance }}</td>
                <td>{{ etape.libelle }}</td>
                <td>
                    <a href="{{ path('app_etape_show', {'id': etape.id}) }}">show</a>
                    <a href="{{ path('app_etape_edit', {'id': etape.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="4">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('app_etape_new') }}">Create new</a>
{% endblock %}

templates/etape/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Etape{% endblock %}

{% block body %}
    <h1>Create new Etape</h1>

    {{ include('etape/_form.html.twig') }}

    <a href="{{ path('app_etape_index') }}">back to list</a>
{% endblock %}

templates/etape/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Etape{% endblock %}

{% block body %}
    <h1>Etape</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ etape.id }}</td>
            </tr>
            <tr>
                <th>Texte_ambiance</th>
                <td>{{ etape.texteAmbiance }}</td>
            </tr>
            <tr>
                <th>Libelle</th>
                <td>{{ etape.libelle }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_etape_index') }}">back to list</a>

    <a href="{{ path('app_etape_edit', {'id': etape.id}) }}">edit</a>

    {{ include('etape/_delete_form.html.twig') }}
{% endblock %}